### ISSUE TITLE
Error when ajaxUpload Class 'common\models\Box' not found

### ISSUE THREAD

**Issue by raditzlawliet** [zxbodya/yii2-gallery-manager#10]
Hello, i'm facing same trouble. when ajax 
I'm using inspector chrome, and the error it's 
<code> Class 'common\models\Box' not found </code>
in behavior i'm copy from your tutorial readme.md
```
return $img->copy()->thumbnail(new Box(200, 200));
```

When i'm open new tab it's change error to <code>Trying to get property of non-object</code> (maybe cause no file uploaded).

I didn't know what is Box Class ? and how to use it or include it ?

and I already correct code 
```
use zxbodya\yii2\galleryManager\galleryBehavior;
```
to
```
use zxbodya\yii2\galleryManager\GalleryBehavior;
```

here my behavior
```
use zxbodya\yii2\galleryManager\GalleryBehavior;

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'galleryBehavior' => [
                 'class' => GalleryBehavior::className(),
                 'type' => 'toilet',
                 'extension' => 'jpg',
                 'directory' => Yii::getAlias('@webroot') . '/images/toilet/gallery',
                 'url' => Yii::getAlias('@web') . '/images/toilet/gallery',
                 'versions' => [
                     'small' => function ($img) {
                         /** @var ImageInterface $img */
                         return $img
                             ->copy()
                             ->thumbnail(new Box(200, 200));
                     },
                     'medium' => function ($img) {
                         /** @var ImageInterface $img */
                         $dstSize = $img->getSize();
                         $maxWidth = 800;
                         if ($dstSize->getWidth() > $maxWidth) {
                             $dstSize = $dstSize->widen($maxWidth);
                         }
                         return $img
                             ->copy()
                             ->resize($dstSize);
                     },
                 ]
             ]
        ]);
    }
```

Controller
```
use zxbodya\yii2\galleryManager\GalleryManagerAction;

public function actions()
    {
        return [
           'galleryApi' => [
               'class' => GalleryManagerAction::className(),
               // mappings between type names and model classes (should be the same as in behaviour)
               'types' => [
                   'toilet' => Toilet::className()
               ]
           ],
        ];
    }
```

_form.php
```
use zxbodya\yii2\galleryManager\GalleryManager;

        <?php 
	if ($model->isNewRecord) {
	    echo 'Can not upload images for new record';
	} else {
	    echo GalleryManager::widget(
	        [
	            'model' => $model,
	            'behaviorName' => 'galleryBehavior',
	            'apiRoute' => 'toilet/galleryApi'
	        ]
	    );
	}
	?>


```
some Stack Trace while new tab
```
exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in E:\xampp\htdocs\web\advanced\vendor\zxbodya\yii2-gallery-manager\GalleryManagerAction.php:102
Stack trace:
#0 E:\xampp\htdocs\web\advanced\vendor\zxbodya\yii2-gallery-manager\GalleryManagerAction.php(102): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 102, Array)
#1 E:\xampp\htdocs\web\advanced\vendor\zxbodya\yii2-gallery-manager\GalleryManagerAction.php(59): zxbodya\yii2\galleryManager\GalleryManagerAction->actionAjaxUpload()
#2 [internal function]: zxbodya\yii2\galleryManager\GalleryManagerAction->run('ajaxUpload')
#3 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array)
#5 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('galleryApi', Array)
#6 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('toilet/galleryA...', Array)
#7 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 E:\xampp\htdocs\web\advanced\frontend\web\index.php(18): yii\base\Application->run()
#9 {main}
```

**Comment by zxbodya** [comment]
Oh, forget to mention... - It is classes from Imagine.
There was following in example model:

```
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
```

**Comment by zxbodya** [comment]
Updated readme file, to prevent such errors :)

**Comment by raditzlawliet** [comment]
Okey, thanks. some problem solve again :+1: 

another problem again, I open a new issue or ?... 

```
Imagine\Exception\RuntimeException

imagejpeg(E:/xampp/htdocs/webadvanced/frontend/web/images/toilet/gallery/1\30\original.jpg): failed to open stream: No such file or directory
↵
Caused by: ErrorException

imagejpeg(E:/xampp/htdocs/web/advanced/frontend/web/images/toilet/gallery/1\30\original.jpg): failed to open stream: No such file or directory

in E:\xampp\htdocs\web\advanced\vendor\imagine\imagine\lib\Imagine\Gd\Image.php at line 584
```

Looks like when upload new image, it create folder only until <code>images/Model/gallery</code> but the <code>idFolder</code> and <code>versionsFolder</code> didn't created and Uploaded image doesn't uploaded.

I'm trying to test create folder manually ex. next id is 25, then <code>images/Model/gallery/25</code> and upload works. (only for next increment id 25).

after that I got same error again, file not found.

**Comment by zxbodya** [comment]
Problem is that I have not tested it on windows, so there is a problem with filenames: `gallery/1\30\`.

I have changed directory separators to slashes - as I remember, it should work on windows. But I am not sure - so, try it.

**Comment by raditzlawliet** [comment]
Great, after update, ajaxUpload working properly on windows.

Thank you, later I'm trying again.
