### ISSUE TITLE
Error in actionAjaxUpload

### ISSUE THREAD

**Issue by BrunoAl25** [zxbodya/yii2-gallery-manager#6]
When i add an image for upload gives the error "Trying to get property of non-object" in the line $image = $this->behavior->addImage($fileName)

I check it out in FireBug and i can see all the properties from the image , but in the addImage simples crash.

**Comment by zxbodya** [comment]
Looks weird...
Likely you have something wrong in configuration... - can you show your code related to gallery manager?

**Comment by zxbodya** [comment]
Looks like I found a bug:
`use zxbodya\yii2\galleryManager\galleryBehavior;`

`galleryBehavior` should be `GalleryBehavior`

**Comment by raditzlawliet** [comment]
Hello, i'm facing same trouble. when ajax 
```
Trying to get property of non-object
```

and I already correct code 
```
use zxbodya\yii2\galleryManager\galleryBehavior;
```
to
```
use zxbodya\yii2\galleryManager\GalleryBehavior;
```

here my behavior
```
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'galleryBehavior' => [
                 'class' => GalleryBehavior::className(),
                 'type' => 'toilet',
                 'extension' => 'jpg',
                 'directory' => Yii::getAlias('@webroot') . '/images/toilet/gallery',
                 'url' => Yii::getAlias('@web') . '/images/toilet/gallery',
                 'versions' => [
                     'small' => function ($img) {
                         /** @var ImageInterface $img */
                         return $img
                             ->copy()
                             ->thumbnail(new Box(200, 200));
                     },
                     'medium' => function ($img) {
                         /** @var ImageInterface $img */
                         $dstSize = $img->getSize();
                         $maxWidth = 800;
                         if ($dstSize->getWidth() > $maxWidth) {
                             $dstSize = $dstSize->widen($maxWidth);
                         }
                         return $img
                             ->copy()
                             ->resize($dstSize);
                     },
                 ]
             ]
        ]);
    }
```

some Stack Trace
```
exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in E:\xampp\htdocs\web\advanced\vendor\zxbodya\yii2-gallery-manager\GalleryManagerAction.php:102
Stack trace:
#0 E:\xampp\htdocs\web\advanced\vendor\zxbodya\yii2-gallery-manager\GalleryManagerAction.php(102): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', 'E:\\xampp\\htdocs...', 102, Array)
#1 E:\xampp\htdocs\web\advanced\vendor\zxbodya\yii2-gallery-manager\GalleryManagerAction.php(59): zxbodya\yii2\galleryManager\GalleryManagerAction->actionAjaxUpload()
#2 [internal function]: zxbodya\yii2\galleryManager\GalleryManagerAction->run('ajaxUpload')
#3 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#4 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array)
#5 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('galleryApi', Array)
#6 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('toilet/galleryA...', Array)
#7 E:\xampp\htdocs\web\advanced\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 E:\xampp\htdocs\web\advanced\frontend\web\index.php(18): yii\base\Application->run()
#9 {main}
```
